### ISSUE TITLE
velum external pillar does not load

### ISSUE THREAD

**Issue by jgleissner** [kubic-project/salt#405]
When trying to access the pillar items provided via the external velum pillar, I get no data. The salt-master container log contains the following:

```
{"log":"16:00:50,353 [PROFILE ] Time (in seconds) to render '/srv/pillar/cloud.sls' using 'yaml
' renderer: 0.00510215759277\n","stream":"stderr","time":"2018-02-27T16:00:50.354028037Z"}
{"log":"16:00:50,370 [INFO    ] Loaded velum pillar module\n","stream":"stderr","time":"2018-02
-27T16:00:50.37046686Z"}
{"log":"16:00:50,513 [DEBUG   ] Failed to import module kubernetes:\n","stream":"stderr","time"
:"2018-02-27T16:00:50.513395674Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2018-02-27T16:00:50.513
42746Z"}
{"log":"  File \"/usr/lib/python2.7/site-packages/salt/loader.py\", line 1333, in _load_module\
n","stream":"stderr","time":"2018-02-27T16:00:50.513432637Z"}
{"log":"    mod = imp.load_module(mod_namespace, fn_, fpath, desc)\n","stream":"stderr","time":
"2018-02-27T16:00:50.513437312Z"}
{"log":"  File \"/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py\", line 67, in \u0
03cmodule\u003e\n","stream":"stderr","time":"2018-02-27T16:00:50.513441432Z"}
{"log":"    from kubernetes.client import AppsV1beta1Deployment\n","stream":"stderr","time":"20
18-02-27T16:00:50.513446319Z"}
{"log":"  File \"/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py\", line 67, in \u0
03cmodule\u003e\n","stream":"stderr","time":"2018-02-27T16:00:50.51345018Z"}
{"log":"    from kubernetes.client import AppsV1beta1Deployment\n","stream":"stderr","time":"20
18-02-27T16:00:50.513454406Z"}
{"log":"ImportError: No module named client\n","stream":"stderr","time":"2018-02-27T16:00:50.51
3458254Z"}
{"log":"16:00:50,631 [DEBUG   ] Module DSC: Only available on Windows systems\n","stream":"stde
rr","time":"2018-02-27T16:00:50.632140745Z"}
{"log":"16:00:50,636 [DEBUG   ] Module PSGet: Only available on Windows systems\n","stream":"st
derr","time":"2018-02-27T16:00:50.637058699Z"}
{"log":"16:00:50,970 [DEBUG   ] Could not LazyLoad redis.get_key: 'redis.get_key' is not availa
ble.\n","stream":"stderr","time":"2018-02-27T16:00:50.970732683Z"}
{"log":"16:00:50,973 [DEBUG   ] Could not LazyLoad velum.ext_pillar: 'velum.ext_pillar' is not 
available.\n","stream":"stderr","time":"2018-02-27T16:00:50.974088542Z"}
{"log":"16:00:50,973 [CRITICAL] Specified ext_pillar interface velum is unavailable\n","stream"
:"stderr","time":"2018-02-27T16:00:50.9741117Z"}
```
The `__virtual__` function of velum.py is obviously executed (hence the "Loaded velum pillar module"), but it doesn't work. That's with salt 2016.11.4 as provided by SLE12.

**Comment by ereslibre** [comment]
Does running a `salt '*' saltutil.sync_all refresh=True` on the salt-master improve the situation? We do that as one of the first steps of the orchestration and from that point on the `Specified ext_pillar interface velum is unavailable` error goes away.

**Comment by jgleissner** [comment]
Still getting "[CRITICAL] Specified ext_pillar interface velum is unavailable". Anything else I could try?

**Comment by jgleissner** [comment]
If I copy /usr/share/salt/kubernetes/salt/_pillar/velum.py to /usr/lib/python2.7/site-packages/salt/pillar/, the velum pillar works. It's a little odd, because the "Loaded velum pillar module" message indicates that it did find the file.

**Comment by ereslibre** [comment]
Sorry for the delay, running `salt-run saltutil.sync_pillar` on the salt-master makes the error disappear?

**Comment by jgleissner** [comment]
That seem to do the trick, thanks.

**Comment by ereslibre** [comment]
Thank you.

**Comment by jgleissner** [comment]
Hang on, does that mean that salt runner is executed during orchestration? `salt '*' saltutil.sync_all refresh=True` didn't actually help.

And come to think of it, that would be too late in the process anyway for public cloud support, as it requires the velum pillar to be operational for creating nodes, i.e. before orchestration. Would it be ok if we added that salt runner call right before creating cluster nodes?

**Comment by ereslibre** [comment]
Yes, because `sync_pillar` is somewhat special:

- `saltutil.sync_all`: https://github.com/saltstack/salt/blob/140ef4d6b9c188adb715c47e6fbf832bc0b47a14/salt/modules/saltutil.py#L663-L722
- `saltutil.sync_pillar`: https://github.com/saltstack/salt/blob/140ef4d6b9c188adb715c47e6fbf832bc0b47a14/salt/modules/saltutil.py#L628-L660

If you see, both check that `__opts__['file_client'] == 'local'`. What we do on the orchestration is to run `saltutil.sync_pillar` in the context of the salt-master:

https://github.com/kubic-project/salt/blob/292b025681915a6ad4d7378624385d231f2f21d4/salt/orch/kubernetes.sls#L34-L41

(note the `salt.runner` there). So, if you need this before calling to the orchestration I'd say we need to call to `saltutil.sync_pillar` with a [`runner` client](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html) using the `salt-api`. That way, we'd force this `sync_pillar` way before calling to the orchestration and you can work with the pillar normally.

**Comment by ereslibre** [comment]
Please note: I'm suggesting we call to `saltutil.sync_pillar` using the `salt-api` in addition to keeping the snippet above on the orchestration (it's still good to have it there).

**Comment by ereslibre** [comment]
Also,

> Would it be ok if we added that salt runner call right before creating cluster nodes?

I don't know what does your workflow look like. In any case, we can talk about that if you are interested, but I'd say on a certain place in Velum (after some settings have been added by the user) looks a good place. Because I'm missing some context regarding the statement `requires the velum pillar to be operational for creating nodes`.

**Comment by ereslibre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [velum external pillar does not load](https://trello.com/c/VFzO6yfT/715-velum-external-pillar-does-not-load)

**Comment by jgleissner** [comment]
Great, thanks for the information. I'll open a pull request for the sync_pillar call.
